In [1]:
import numpy as np

# Numpy

In [2]:
# Crear array de 1 dimencion
arr1 = np.array([1, 2, 3, 4 , 5, 6])
print('Array de 1 dimención:', arr1)
print('Forma(shape): ', arr1.shape)
print('Tipo de datos(dtype): ', arr1.dtype)

Array de 1 dimención: [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipo de datos(dtype):  int64


In [3]:
# Cambiar la forma del arreglo de una matriz de x filas y x columnas
arr2 = arr1.reshape((2, 3))
print('Array de 2 dimención:\n', arr2)
print('Forma(shape): ', arr2.shape)
print('Tipo de datos(dtype): ', arr2.dtype)

Array de 2 dimención:
 [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Tipo de datos(dtype):  int64


In [4]:
# Crear array de 2 dimenciones con numero aleatorios
matrix = np.random.randint(0, 1000, size=(4, 4))
print('Array de 2 dimención aleatoria:\n', matrix)
print('Forma(shape): ', matrix.shape)
print('Tipo de datos(dtype): ', matrix.dtype)

Array de 2 dimención aleatoria:
 [[597 452 420 118]
 [717  78 872 590]
 [668 205 180  65]
 [440 326 201 778]]
Forma(shape):  (4, 4)
Tipo de datos(dtype):  int32


In [5]:
# Crear un arreglo de 2 dmienciones a partir de una lista de listas
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [6]:
# Crear array con 0 con una forma de 3, 4
arrr = np.zeros((3, 4))
arrr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# Con 1
arrrr = np.ones((3, 4))
arrrr[1, 1] = 10
arrrr

array([[ 1.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [8]:
# Crear una matriz de identidad
arrrr = np.eye(4)
arrrr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# Crear una array de 3 dimenciones
ar = np.zeros((2, 3, 4))
ar

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])
ar1, ar2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [11]:
# Concatenar arreglos originalmente
ar_h = np.hstack((ar1, ar2))
ar_h, 'Horizontal'

(array([[1, 2, 5, 6],
        [3, 4, 7, 8]]),
 'Horizontal')

In [12]:
ar_v = np.vstack((ar1, ar2))
ar_v, 'Vertical'

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 'Vertical')

In [13]:
# Operaciones
ay = np.array([1, 2, 3, 4, 5])
ay

array([1, 2, 3, 4, 5])

In [14]:
# Suma
suma = np.sum(ay)
suma

np.int64(15)

In [15]:
# Promedio
promedio = np.mean(ay)
promedio

np.float64(3.0)

In [16]:
# Mediana
mediana = np.median(ay)
mediana

np.float64(3.0)

In [17]:
# Producto
producto = np.prod(ay)
producto

np.int64(120)

In [19]:
# Desviación estandar
desv_est = np.std(ay)
desv_est

np.float64(1.4142135623730951)

In [20]:
# Varianza
var = np.var(ay)
var

np.float64(2.0)

In [21]:
# Minimo
minimo = np.min(ay)
# Maximo
maximo = np.max(ay)
minimo, maximo

(np.int64(1), np.int64(5))

In [22]:
cumsum = np.cumsum(ay)
cumsum

array([ 1,  3,  6, 10, 15])

In [23]:
# Operaciones elemento : elemento
ay + ay

array([ 2,  4,  6,  8, 10])

In [24]:
ay - ay

array([0, 0, 0, 0, 0])

In [25]:
ay * ay

array([ 1,  4,  9, 16, 25])

In [26]:
ay / ay

array([1., 1., 1., 1., 1.])